package view;

import controller.AgendaController;
import model.ContatoTM;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import model.Agenda;

public class AgendaView extends javax.swing.JFrame implements Observer{
    ContatoTM modelo;
    AgendaController controller;
    
    public AgendaView() {
        Agenda.getInstance().addObserver(this);
        initComponents();
        setLocationRelativeTo(null);
        controller = AgendaController.getInstance();
        controller.initialized();
        botoes(true,false,false,true);
        PainelGrupos.setVisible(false);
    }    

    public void display(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgendaView view = new AgendaView();
                Agenda.getInstance().addObserver(view);                
                view.setVisible(true);
            }
        });
    }
    
    private void loadTable(){
        modelo = new ContatoTM(controller.getContatos());
        tbContatos.setModel(modelo);
        
        tbContatos.getColumnModel().getColumn(0).setPreferredWidth(350);
        tbContatos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbContatos.getColumnModel().getColumn(1).setPreferredWidth(100);
    }
    
    private void loadComboBox(){
        ArrayList<String> grupos = controller.getGrupo();
        for(int i=0; i<grupos.size(); i++)
            cbGrupos.addItem(grupos.get(i));
    }
    
    private void loadTableGrupo(){
        
        try{
            modelo = new ContatoTM(controller.getContatos(cbGrupos.getSelectedItem().toString()));
            tbGrupos.setModel(modelo);   

        }catch(NullPointerException e){
            
        }
        tbGrupos.getColumnModel().getColumn(0).setPreferredWidth(350);
        tbGrupos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbGrupos.getColumnModel().getColumn(1).setPreferredWidth(100);

    }
    
    private void botoes(boolean N, boolean S, boolean C, boolean G){
        btNovo.setEnabled(N);
        btSalvar.setEnabled(S);
        btCancelar.setEnabled(C);
        btGrupos.setEnabled(G);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbContatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btGrupos = new javax.swing.JButton();
        PainelGrupos = new javax.swing.JPanel();
        btInserirNoGrupo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGrupos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbGrupos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfNovoGrupo = new javax.swing.JTextField();
        btNovoGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbContatos);
        if (tbContatos.getColumnModel().getColumnCount() > 0) {
            tbContatos.getColumnModel().getColumn(0).setPreferredWidth(350);
            tbContatos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbContatos.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Email:");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btGrupos.setText("Grupos");
        btGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btGrupos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar)
                    .addComponent(btNovo)
                    .addComponent(btGrupos))
                .addContainerGap())
        );

        PainelGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));

        btInserirNoGrupo.setText("Inserir");
        btInserirNoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirNoGrupoActionPerformed(evt);
            }
        });

        tbGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGruposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbGrupos);
        if (tbGrupos.getColumnModel().getColumnCount() > 0) {
            tbGrupos.getColumnModel().getColumn(0).setPreferredWidth(350);
            tbGrupos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbGrupos.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel4.setText("Grupo:");

        cbGrupos.setToolTipText("");
        cbGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGruposItemStateChanged(evt);
            }
        });
        cbGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGruposActionPerformed(evt);
            }
        });

        jLabel5.setText("Novo Grupo:");

        btNovoGrupo.setText("Criar");
        btNovoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelGruposLayout = new javax.swing.GroupLayout(PainelGrupos);
        PainelGrupos.setLayout(PainelGruposLayout);
        PainelGruposLayout.setHorizontalGroup(
            PainelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(PainelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelGruposLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btInserirNoGrupo))
                    .addGroup(PainelGruposLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNovoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovoGrupo)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        PainelGruposLayout.setVerticalGroup(
            PainelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserirNoGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PainelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNovoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovoGrupo))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(PainelGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContatosMouseClicked
        botoes(true,false,false,true);
        int index = tbContatos.getSelectedRow();
        if(index>=0 && index<modelo.getRowCount()){
            String temp[] = modelo.getAluno(index);
            tfNome.setText(temp[0]);
            tfEmail.setText(temp[1]);
            tfTelefone.setText(temp[2]);
        }
    }//GEN-LAST:event_tbContatosMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tfNome.setText("");
        tfEmail.setText("");
        tfTelefone.setText("");
        botoes(false,true,true,false);
        PainelGrupos.setVisible(false);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if( controller.salvarContato(tfNome.getText(),tfEmail.getText(), tfTelefone.getText()) ){
            JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!");
        }else
            JOptionPane.showMessageDialog(this, "Erro ao salvar o aluno!");
        
        botoes(true,false,false,true);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        botoes(true,false,false,true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGruposActionPerformed
        PainelGrupos.setVisible(true);
    }//GEN-LAST:event_btGruposActionPerformed

    private void tbGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGruposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbGruposMouseClicked

    private void cbGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGruposItemStateChanged
    }//GEN-LAST:event_cbGruposItemStateChanged

    private void btNovoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoGrupoActionPerformed
        String g = tfNovoGrupo.getText();
        cbGrupos.addItem(g);
        tfNovoGrupo.setText("");
        controller.salvaGrupo(g);
    }//GEN-LAST:event_btNovoGrupoActionPerformed

    private void btInserirNoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirNoGrupoActionPerformed
        controller.auterarContato((String)cbGrupos.getSelectedItem(), tbContatos.getSelectedRow());
    }//GEN-LAST:event_btInserirNoGrupoActionPerformed

    private void cbGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGruposActionPerformed
        controller.atualizar();
    }//GEN-LAST:event_cbGruposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelGrupos;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGrupos;
    private javax.swing.JButton btInserirNoGrupo;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btNovoGrupo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbContatos;
    private javax.swing.JTable tbGrupos;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNovoGrupo;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        loadTable();
        loadTableGrupo();
        if(cbGrupos.getItemCount() == 0)
            loadComboBox();
    }
}